version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    ignore:
      # Ignore any major update for react router
      - dependency-name: "react-router-dom"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    schedule:
      # Check for updates managed once a week
      interval: "weekly"
      day: "thursday"
      time: "05:00"
      timezone: "America/Indiana/Indianapolis"
    versioning-strategy: increase-if-necessary
    open-pull-requests-limit: 20
