pull_request_rules:
  - name: Automatically merge dependapot PRs with passing tests
    conditions:
      - author=dependabot[bot]
      - status-success~=test
    actions:
      merge:
        method: squash